language: node_js

node_js:
  - '0.10'

services:
  - mongodb

before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install sass --version "=3.2.14"'
  - 'gem install compass --version "=0.12.2"'

script:
  - grunt test
