language: node_js

node_js:
  - '0.10'

services:
  - mongodb

addons:
  firefox: "17.0"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install sass --version "=3.2.14"'
  - 'gem install compass --version "=0.12.2"'

script:
  - grunt test
